### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by thelong0705** [thelong0705/jisho_tooltip#2]
- [x] wrong tooltip position when scrolling vertically
- [x] loading go out of screen when highlight word in the right edge
- [x] catch error when fetching api
- [x] add hotkey to toggle tooltip
- [x] improve tooltip UI
- [x] no katakana reading
- [x] word have many meanings
- [x] text span 2 lines
- [x] remove hard coded value
- [x] wrong tooltip position when scrolling horizontally
- [x] arrow is not middle of word in the right edge
- [x] under highlight not under word
- [x] click bug
- [x] logo
- [x] refactor code
- [x] remove clicked extension
- [x] unique class name
- [x] update readme
- [x] add link to redirect to jisho
- [x] release
- [x] highlight long line 
- [x] esa bug ?
